services:
    control-code:
        build:
            context: ./control-code
        network_mode: host
        privileged: true
        restart: always
        volumes:
            - ./control-code:/app

    interface:
        build:
            context: ./interface
        network_mode: host
        restart: always
        depends_on:
            - control-code
