services:
    control-code:
        build:
            context: ./control-code
        network_mode: host
        volumes:
            - ./control-code:/app

    interface:
        build:
            context: ./interface
        network_mode: host
        depends_on:
            - control-code
